version: '3.8'

services:
 nginx:
  image: nginx:latest
  ports:
   - '80:80'
  volumes:
   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - frontend
   - backend

 frontend:
  image: node:22-slim
  command: sh -c "npm install && npm run dev"
  user: node
  working_dir: /app
  volumes:
   - .:/app
  environment:
   - HOST=0.0.0.0
   - APP_URL=http://localhost
  ports:
   - '5173:5173'

 backend:
  build:
   context: .
   dockerfile: docker/php/Dockerfile
  volumes:
   - .:/var/www
  working_dir: /var/www
  command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
  expose:
   - '8000'
  environment:
   - CHOKIDAR_USEPOLLING=true

 mysql:
  image: mysql:8.0
  ports:
   - '3306:3306'
  environment:
   - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
   - MYSQL_DATABASE=${DB_DATABASE}
   - MYSQL_USER=${DB_USERNAME}
   - MYSQL_PASSWORD=${DB_PASSWORD}
  volumes:
   - mysql_data:/var/lib/mysql

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - '8080:80'
  environment:
   - PMA_HOST=mysql
   - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
 mysql_data:
