version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
      args:
        - UID=${USER_ID}
        - GID=${GROUP_ID}
    container_name: progressa_app
    command: bash -c "composer install && php-fpm"
    restart: unless-stopped
    environment:
      APP_ENV: production
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - progressa_net

  frontend:
    image: node:22-slim
    container_name: progressa_frontend
    working_dir: /var/www
    user: node
    environment:
      - APP_ENV=production
      - NODE_ENV=production
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:latest
    container_name: progressa_nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - progressa_net

  mysql:
    image: mysql:8.0
    container_name: progressa_mysql
    restart: unless-stopped
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - progressa_net

volumes:
  mysql_data:

networks:
  progressa_net:
    driver: bridge
